import { Renderer2, ElementRef, OnInit, AfterViewInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { MediaObserver } from '@angular/flex-layout';
import { BehaviorSubject, Observable } from 'rxjs';
import { MatSidenav } from '@angular/material';
import { PipMediaService } from '../media/shared/media.service';
import { PipSidenavService } from '../sidenav/shared/sidenav.service';
import { PipRightnavService } from '../rightnav/shared/rightnav.service';
export declare class PipMainLayoutAltComponent implements OnInit, AfterViewInit, OnDestroy {
    private renderer2;
    private elRef;
    private cd;
    private mainMedia;
    sidenavService: PipSidenavService;
    rightnavService: PipRightnavService;
    private media;
    pipContainer: any;
    sidenav: MatSidenav;
    rightnav: MatSidenav;
    private listener;
    private element;
    private subs;
    uFloating$: BehaviorSubject<boolean>;
    small$: BehaviorSubject<boolean>;
    activeSidenav$: Observable<boolean>;
    constructor(renderer2: Renderer2, elRef: ElementRef, cd: ChangeDetectorRef, mainMedia: PipMediaService, sidenavService: PipSidenavService, rightnavService: PipRightnavService, media: MediaObserver);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    backdropClick(): void;
    private onResize;
}
